version: '3.9'
services:
    db:
        image: postgres:12.4
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: test
        ports:
            - 5433:5433
        volumes:
            - pgdata:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - 5434:80
        volumes:
            - ./pgadmin4-servers.json:/pgadmin4/servers.json:ro

volumes:
    pgdata:
